export { default as CoachDashboardHeader } from './CoachDashboardHeader'
export { default as CoachDashboardTabs } from './CoachDashboardTabs'
export { default as PlayersTab } from './PlayersTab'
export { default as TrainingTab } from './TrainingTab'
export { default as StatsTab } from './StatsTab'
export { default as AttendanceTab } from './AttendanceTab'
export { default as PlayerDetailPanel } from './PlayerDetailPanel'
export { default as TrainingModal } from './TrainingModal'
export { default as EvaluationModal } from './EvaluationModal'
export { default as AttendanceModal } from './AttendanceModal'
export { useCoachDashboard } from './useCoachDashboard'
export type { Player, Training, AttendanceRecord, Evaluation, NewTraining, ActiveTab } from './types'